[
{"mod" : "BMW 7 Series", "cnt" : "384"},
{"mod" : "Mercedes-Benz E-Class", "cnt" : "751"},
{"mod" : "Honda Civic", "cnt" : "938"},
{"mod" : "Chevrolet Camaro", "cnt" : "515"},
{"mod" : "Honda Accord", "cnt" : "773"},
{"mod" : "Mazda 3", "cnt" : "172"},
{"mod" : "Kia Sedona", "cnt" : "93"},
{"mod" : "Lexus ES 300h", "cnt" : "85"},
{"mod" : "Acura MDX", "cnt" : "169"},
{"mod" : "Ford Mustang", "cnt" : "777"},
{"mod" : "Infiniti QX60", "cnt" : "80"},
{"mod" : "Toyota 4Runner", "cnt" : "140"},
{"mod" : "Volkswagen Passat", "cnt" : "241"},
{"mod" : "Toyota Sienna", "cnt" : "770"},
{"mod" : "Ford Fusion", "cnt" : "432"},
{"mod" : "BMW 4 Series", "cnt" : "246"},
{"mod" : "Chevrolet Volt", "cnt" : "281"},
{"mod" : "Nissan Leaf", "cnt" : "411"},
{"mod" : "BMW M3", "cnt" : "229"},
{"mod" : "Nissan Quest", "cnt" : "101"},
{"mod" : "Dodge Nitro", "cnt" : "17"},
{"mod" : "Toyota Camry", "cnt" : "1160"},
{"mod" : "Hyundai Sonata", "cnt" : "663"},
{"mod" : "smart fortwo", "cnt" : "469"},
{"mod" : "BMW 3 Series", "cnt" : "1684"},
{"mod" : "Jeep Grand Cherokee", "cnt" : "383"},
{"mod" : "Audi A3", "cnt" : "214"},
{"mod" : "Lexus GS 350", "cnt" : "198"},
{"mod" : "Dodge Grand Caravan", "cnt" : "371"},
{"mod" : "Honda Fit", "cnt" : "220"},
{"mod" : "Honda Element", "cnt" : "91"},
{"mod" : "Nissan Sentra", "cnt" : "311"},
{"mod" : "Chevrolet Spark", "cnt" : "220"},
{"mod" : "Chevrolet Pickup", "cnt" : "8"},
{"mod" : "Jeep Compass", "cnt" : "45"},
{"mod" : "Nissan Altima", "cnt" : "750"},
{"mod" : "Porsche Cayman", "cnt" : "96"},
{"mod" : "Ram CV Tradesman", "cnt" : "22"},
{"mod" : "Mazda MX-5 Miata", "cnt" : "90"},
{"mod" : "Honda CR-V", "cnt" : "334"},
{"mod" : "Dodge Caravan", "cnt" : "4"},
{"mod" : "Ford Focus", "cnt" : "470"},
{"mod" : "Toyota Corolla", "cnt" : "785"},
{"mod" : "BMW M5", "cnt" : "135"},
{"mod" : "Cadillac Escalade ESV", "cnt" : "227"},
{"mod" : "Mercedes-Benz S-Class", "cnt" : "458"},
{"mod" : "Audi R8", "cnt" : "100"},
{"mod" : "Toyota Prius", "cnt" : "1515"},
{"mod" : "Mercedes-Benz M-Class", "cnt" : "278"},
{"mod" : "Nissan Versa", "cnt" : "156"},
{"mod" : "Audi Q7", "cnt" : "114"},
{"mod" : "Kia Optima Hybrid", "cnt" : "11"},
{"mod" : "BMW 6 Series Gran Coupe", "cnt" : "83"},
{"mod" : "BMW 5 Series", "cnt" : "687"},
{"mod" : "Mazda 6", "cnt" : "104"},
{"mod" : "FIAT 500", "cnt" : "308"},
{"mod" : "Honda Pilot", "cnt" : "198"},
{"mod" : "Chevrolet Suburban", "cnt" : "362"},
{"mod" : "Land Rover Range Rover Sport", "cnt" : "432"},
{"mod" : "Mazda 2", "cnt" : "13"},
{"mod" : "Volkswagen Jetta", "cnt" : "613"},
{"mod" : "Porsche 911", "cnt" : "375"},
{"mod" : "Toyota Tundra", "cnt" : "158"},
{"mod" : "Toyota Camry Solara", "cnt" : "39"},
{"mod" : "Mercedes-Benz C-Class", "cnt" : "966"},
{"mod" : "Lexus IS 350 C", "cnt" : "13"},
{"mod" : "Mercedes-Benz GLE-Class", "cnt" : "93"},
{"mod" : "Mitsubishi Outlander", "cnt" : "56"},
{"mod" : "Acura TSX", "cnt" : "86"},
{"mod" : "Toyota Camry Hybrid", "cnt" : "206"},
{"mod" : "Dodge Magnum", "cnt" : "9"},
{"mod" : "Mercedes-Benz CLA-Class", "cnt" : "202"},
{"mod" : "Cadillac ATS", "cnt" : "90"},
{"mod" : "Audi S4", "cnt" : "118"},
{"mod" : "Nissan 350Z", "cnt" : "60"},
{"mod" : "Mercedes-Benz 300-Class", "cnt" : "20"},
{"mod" : "Hyundai Veloster", "cnt" : "63"},
{"mod" : "Ford Ranger", "cnt" : "53"},
{"mod" : "Mercedes-Benz SLK-Class", "cnt" : "82"},
{"mod" : "BMW i3", "cnt" : "217"},
{"mod" : "Chevrolet Aveo", "cnt" : "149"},
{"mod" : "Ford Flex", "cnt" : "54"},
{"mod" : "Toyota Avalon", "cnt" : "67"},
{"mod" : "Ford Excursion", "cnt" : "6"},
{"mod" : "Honda Odyssey", "cnt" : "425"},
{"mod" : "Chevrolet Silverado 1500", "cnt" : "105"},
{"mod" : "Lexus IS 350", "cnt" : "63"},
{"mod" : "Cadillac XTS", "cnt" : "75"},
{"mod" : "Jaguar X-Type", "cnt" : "38"},
{"mod" : "Chevrolet Corvette", "cnt" : "182"},
{"mod" : "Ford Fiesta", "cnt" : "186"},
{"mod" : "Acura TLX", "cnt" : "36"},
{"mod" : "Porsche Cayenne", "cnt" : "297"},
{"mod" : "Cadillac STS", "cnt" : "12"},
{"mod" : "Tesla Model S", "cnt" : "708"},
{"mod" : "BMW X3", "cnt" : "154"},
{"mod" : "Dodge Viper", "cnt" : "24"},
{"mod" : "BMW M4", "cnt" : "166"},
{"mod" : "Kia Borrego", "cnt" : "8"},
{"mod" : "Audi A5", "cnt" : "123"},
{"mod" : "Hyundai Genesis", "cnt" : "129"},
{"mod" : "Subaru Tribeca", "cnt" : "15"},
{"mod" : "Lexus GX 460", "cnt" : "71"},
{"mod" : "Porsche Boxster", "cnt" : "217"},
{"mod" : "Volvo S60", "cnt" : "27"},
{"mod" : "Hyundai Elantra GT", "cnt" : "42"},
{"mod" : "BMW M6 Gran Coupe", "cnt" : "16"},
{"mod" : "MINI Cooper", "cnt" : "407"},
{"mod" : "Chevrolet Corvette Stingray", "cnt" : "159"},
{"mod" : "Mercedes-Benz G-Class", "cnt" : "406"},
{"mod" : "Mercedes-Benz GLC-Class", "cnt" : "19"},
{"mod" : "Nissan Titan", "cnt" : "36"},
{"mod" : "Chevrolet Cruze", "cnt" : "208"},
{"mod" : "Dodge Journey", "cnt" : "47"},
{"mod" : "Dodge Ram Pickup 1500", "cnt" : "68"},
{"mod" : "Ford Explorer", "cnt" : "116"},
{"mod" : "Lexus RX 330", "cnt" : "32"},
{"mod" : "Chevrolet Tahoe", "cnt" : "137"},
{"mod" : "Jeep Wrangler", "cnt" : "844"},
{"mod" : "Dodge Challenger", "cnt" : "257"},
{"mod" : "MINI Cooper Countryman", "cnt" : "28"},
{"mod" : "Maserati Ghibli", "cnt" : "212"},
{"mod" : "Subaru WRX", "cnt" : "111"},
{"mod" : "Chrysler Town and Country", "cnt" : "218"},
{"mod" : "Toyota Prius c", "cnt" : "311"},
{"mod" : "Cadillac Escalade", "cnt" : "250"},
{"mod" : "Volvo XC90", "cnt" : "33"},
{"mod" : "Chrysler 300", "cnt" : "320"},
{"mod" : "BMW X5", "cnt" : "461"},
{"mod" : "Kia Soul", "cnt" : "156"},
{"mod" : "Hyundai Elantra", "cnt" : "312"},
{"mod" : "Infiniti G37", "cnt" : "49"},
{"mod" : "FIAT 500e", "cnt" : "107"},
{"mod" : "Audi A7", "cnt" : "86"},
{"mod" : "Kia Forte", "cnt" : "130"},
{"mod" : "Kia Optima", "cnt" : "236"},
{"mod" : "Scion xB", "cnt" : "25"},
{"mod" : "Dodge Charger", "cnt" : "205"},
{"mod" : "Hyundai Sonata Hybrid", "cnt" : "66"},
{"mod" : "Mercedes-Benz GL-Class", "cnt" : "307"},
{"mod" : "BMW M6", "cnt" : "51"},
{"mod" : "Acura ILX", "cnt" : "42"},
{"mod" : "Mercedes-Benz SL-Class", "cnt" : "69"},
{"mod" : "Pontiac GTO", "cnt" : "20"},
{"mod" : "Lexus CT 200h", "cnt" : "175"},
{"mod" : "Nissan Cube", "cnt" : "38"},
{"mod" : "Subaru Impreza", "cnt" : "152"},
{"mod" : "Infiniti G Sedan", "cnt" : "154"},
{"mod" : "Ram 1500", "cnt" : "168"},
{"mod" : "Scion FR-S", "cnt" : "63"},
{"mod" : "BMW Z4 M", "cnt" : "14"},
{"mod" : "Mercedes-Benz CLS-Class", "cnt" : "154"},
{"mod" : "Infiniti Q50", "cnt" : "288"},
{"mod" : "Land Rover Range Rover Evoque", "cnt" : "111"},
{"mod" : "Lexus ES 350", "cnt" : "245"},
{"mod" : "Ford F-150", "cnt" : "386"},
{"mod" : "Scion tC", "cnt" : "151"},
{"mod" : "Volkswagen New Beetle", "cnt" : "21"},
{"mod" : "GMC Sierra 1500", "cnt" : "16"},
{"mod" : "Hyundai Accent", "cnt" : "70"},
{"mod" : "Jaguar XJ", "cnt" : "41"},
{"mod" : "Cadillac CTS Coupe", "cnt" : "48"},
{"mod" : "Chevrolet Equinox", "cnt" : "108"},
{"mod" : "Volkswagen Routan", "cnt" : "41"},
{"mod" : "Saab 9-3", "cnt" : "48"},
{"mod" : "Mitsubishi Outlander Sport", "cnt" : "62"},
{"mod" : "Nissan Versa Note", "cnt" : "74"},
{"mod" : "Audi A6", "cnt" : "111"},
{"mod" : "Volkswagen Golf R", "cnt" : "19"},
{"mod" : "Chevrolet Sonic", "cnt" : "120"},
{"mod" : "Subaru XV Crosstrek", "cnt" : "59"},
{"mod" : "Toyota Tacoma", "cnt" : "170"},
{"mod" : "Ford Fusion Energi", "cnt" : "38"},
{"mod" : "Volkswagen Eos", "cnt" : "120"},
{"mod" : "Cadillac CTS", "cnt" : "100"},
{"mod" : "BMW 6 Series", "cnt" : "331"},
{"mod" : "Volkswagen Touareg", "cnt" : "53"},
{"mod" : "BMW Z4", "cnt" : "201"},
{"mod" : "Chevrolet Cruze Limited", "cnt" : "54"},
{"mod" : "Lexus IS 250", "cnt" : "259"},
{"mod" : "Toyota Prius v", "cnt" : "147"},
{"mod" : "Mercedes-Benz GLK-Class", "cnt" : "128"},
{"mod" : "Mercedes-Benz CLK-Class", "cnt" : "58"},
{"mod" : "Lincoln Town Car", "cnt" : "37"},
{"mod" : "Mercedes-Benz Metris", "cnt" : "20"},
{"mod" : "Scion xA", "cnt" : "13"},
{"mod" : "Porsche Panamera", "cnt" : "130"},
{"mod" : "Hyundai Santa Fe Sport", "cnt" : "14"},
{"mod" : "Toyota Prius Plug-in", "cnt" : "39"},
{"mod" : "Nissan Frontier", "cnt" : "90"},
{"mod" : "Ford Escape", "cnt" : "89"},
{"mod" : "Mercedes-Benz GLA-Class", "cnt" : "85"},
{"mod" : "GMC Canyon", "cnt" : "21"},
{"mod" : "Buick LaCrosse", "cnt" : "30"},
{"mod" : "Cadillac ELR", "cnt" : "17"},
{"mod" : "Lexus RC 350", "cnt" : "42"},
{"mod" : "Toyota Highlander", "cnt" : "296"},
{"mod" : "Saturn ION", "cnt" : "60"},
{"mod" : "Audi A4", "cnt" : "259"},
{"mod" : "Toyota RAV4", "cnt" : "215"},
{"mod" : "Mazda CX-3", "cnt" : "30"},
{"mod" : "Land Rover LR3", "cnt" : "47"},
{"mod" : "Audi S5", "cnt" : "77"},
{"mod" : "Nissan 370Z", "cnt" : "33"},
{"mod" : "FIAT 500E", "cnt" : "49"},
{"mod" : "BMW X4", "cnt" : "74"},
{"mod" : "Volkswagen Beetle", "cnt" : "15"},
{"mod" : "Ford Expedition", "cnt" : "38"},
{"mod" : "Mazda MAZDASPEED3", "cnt" : "21"},
{"mod" : "Scion iQ", "cnt" : "17"},
{"mod" : "Aston Martin DB9", "cnt" : "18"},
{"mod" : "Audi Q5", "cnt" : "96"},
{"mod" : "Volvo S40", "cnt" : "58"},
{"mod" : "Volkswagen GTI", "cnt" : "52"},
{"mod" : "Jaguar XF", "cnt" : "88"},
{"mod" : "Toyota RAV4 EV", "cnt" : "24"},
{"mod" : "Nissan Pathfinder", "cnt" : "150"},
{"mod" : "GMC Yukon", "cnt" : "81"},
{"mod" : "Infiniti G Coupe", "cnt" : "62"},
{"mod" : "Kia Sportage", "cnt" : "84"},
{"mod" : "Chevrolet Prizm", "cnt" : "7"},
{"mod" : "BMW X6", "cnt" : "179"},
{"mod" : "BMW 2 Series", "cnt" : "18"},
{"mod" : "Hyundai Entourage", "cnt" : "25"},
{"mod" : "Buick Regal", "cnt" : "6"},
{"mod" : "Ford C-Max Energi", "cnt" : "52"},
{"mod" : "Jeep Cherokee", "cnt" : "151"},
{"mod" : "Nissan Juke", "cnt" : "101"},
{"mod" : "Dodge Avenger", "cnt" : "44"},
{"mod" : "Subaru Outback", "cnt" : "85"},
{"mod" : "Kia Soul EV", "cnt" : "17"},
{"mod" : "Chevrolet Impala", "cnt" : "147"},
{"mod" : "Audi S6", "cnt" : "12"},
{"mod" : "Lexus RX 350", "cnt" : "206"},
{"mod" : "Acura TL", "cnt" : "116"},
{"mod" : "Honda CR-Z", "cnt" : "25"},
{"mod" : "Nissan NV200", "cnt" : "9"},
{"mod" : "MINI Cooper Clubman", "cnt" : "27"},
{"mod" : "Suzuki Grand Vitara", "cnt" : "12"},
{"mod" : "Nissan GT-R", "cnt" : "68"},
{"mod" : "Nissan Rogue Select", "cnt" : "11"},
{"mod" : "Infiniti G35", "cnt" : "27"},
{"mod" : "Saturn Sky", "cnt" : "24"},
{"mod" : "VPG MV-1", "cnt" : "5"},
{"mod" : "Dodge Dart", "cnt" : "57"},
{"mod" : "GMC Yukon XL", "cnt" : "124"},
{"mod" : "Oldsmobile Silhouette", "cnt" : "12"},
{"mod" : "BMW 4 Series Gran Coupe", "cnt" : "39"},
{"mod" : "Nissan Murano", "cnt" : "31"},
{"mod" : "Lexus LS 460", "cnt" : "30"},
{"mod" : "Toyota Sequoia", "cnt" : "63"},
{"mod" : "HUMMER H2 SUT", "cnt" : "9"},
{"mod" : "Kia Cadenza", "cnt" : "18"},
{"mod" : "Lincoln MKZ Hybrid", "cnt" : "5"},
{"mod" : "Buick Enclave", "cnt" : "18"},
{"mod" : "Hyundai Tiburon", "cnt" : "22"},
{"mod" : "Lexus NX 200t", "cnt" : "43"},
{"mod" : "BMW 1 Series", "cnt" : "158"},
{"mod" : "Audi A8", "cnt" : "122"},
{"mod" : "Lexus GX 470", "cnt" : "33"},
{"mod" : "Kia Rio", "cnt" : "78"},
{"mod" : "Toyota Matrix", "cnt" : "53"},
{"mod" : "HUMMER H3", "cnt" : "59"},
{"mod" : "Chrysler 200", "cnt" : "94"},
{"mod" : "Chevrolet Malibu", "cnt" : "128"},
{"mod" : "Volkswagen Golf", "cnt" : "54"},
{"mod" : "Mazda CX-5", "cnt" : "114"},
{"mod" : "Pontiac Solstice", "cnt" : "26"},
{"mod" : "Nissan Rogue", "cnt" : "256"},
{"mod" : "Mazda CX-9", "cnt" : "82"},
{"mod" : "Ford C-Max Hybrid", "cnt" : "19"},
{"mod" : "Volvo C70", "cnt" : "35"},
{"mod" : "Kia Spectra", "cnt" : "19"},
{"mod" : "Suzuki SX4", "cnt" : "12"},
{"mod" : "Land Rover Range Rover", "cnt" : "214"},
{"mod" : "Mazda CX-7", "cnt" : "118"},
{"mod" : "Volvo V60", "cnt" : "12"},
{"mod" : "HUMMER H2", "cnt" : "77"},
{"mod" : "Infiniti M35", "cnt" : "77"},
{"mod" : "Lincoln MKX", "cnt" : "32"},
{"mod" : "Buick Verano", "cnt" : "66"},
{"mod" : "Volkswagen CC", "cnt" : "163"},
{"mod" : "Hyundai Santa Fe", "cnt" : "176"},
{"mod" : "Mercedes-Benz CL-Class", "cnt" : "66"},
{"mod" : "Toyota Yaris", "cnt" : "143"},
{"mod" : "Suzuki Forenza", "cnt" : "33"},
{"mod" : "Mazda Protege", "cnt" : "29"},
{"mod" : "Infiniti FX35", "cnt" : "48"},
{"mod" : "Lexus IS F", "cnt" : "35"},
{"mod" : "Ford Five Hundred", "cnt" : "13"},
{"mod" : "Land Rover LR2", "cnt" : "64"},
{"mod" : "Chevrolet Impala Limited", "cnt" : "26"},
{"mod" : "Audi S8", "cnt" : "25"},
{"mod" : "Buick Encore", "cnt" : "30"},
{"mod" : "Nissan Xterra", "cnt" : "57"},
{"mod" : "Mazda MAZDA3", "cnt" : "65"},
{"mod" : "Hyundai Elantra Touring", "cnt" : "30"},
{"mod" : "Nissan Maxima", "cnt" : "85"},
{"mod" : "Acura RDX", "cnt" : "41"},
{"mod" : "Infiniti G Convertible", "cnt" : "15"},
{"mod" : "Cadillac Escalade EXT", "cnt" : "14"},
{"mod" : "Volkswagen Jetta SportWagen", "cnt" : "14"},
{"mod" : "Ford Fusion Hybrid", "cnt" : "96"},
{"mod" : "Chrysler Sebring", "cnt" : "40"},
{"mod" : "Mazda RX-8", "cnt" : "12"},
{"mod" : "Dodge Durango", "cnt" : "72"},
{"mod" : "Subaru Forester", "cnt" : "50"},
{"mod" : "Chevrolet S-10", "cnt" : "32"},
{"mod" : "Mitsubishi i-MiEV", "cnt" : "2"},
{"mod" : "Scion iA", "cnt" : "2"},
{"mod" : "Jeep Commander", "cnt" : "5"},
{"mod" : "GMC Acadia", "cnt" : "60"},
{"mod" : "Ford F-350", "cnt" : "19"},
{"mod" : "Toyota Venza", "cnt" : "48"},
{"mod" : "Jaguar XK", "cnt" : "10"},
{"mod" : "Mitsubishi Lancer Evolution", "cnt" : "11"},
{"mod" : "Lincoln MKZ", "cnt" : "71"},
{"mod" : "Jeep Grand Cherokee SRT", "cnt" : "54"},
{"mod" : "Ford Escape Hybrid", "cnt" : "77"},
{"mod" : "Saturn Astra", "cnt" : "20"},
{"mod" : "Hyundai Genesis Coupe", "cnt" : "57"},
{"mod" : "BMW X1", "cnt" : "108"},
{"mod" : "Infiniti JX", "cnt" : "36"},
{"mod" : "Suzuki Samurai", "cnt" : "26"},
{"mod" : "Land Rover LR4", "cnt" : "35"},
{"mod" : "Ford Edge", "cnt" : "45"},
{"mod" : "Kia Rondo", "cnt" : "45"},
{"mod" : "Ford Crown Victoria", "cnt" : "87"},
{"mod" : "Lexus RX 400h", "cnt" : "34"},
{"mod" : "Lexus LX 570", "cnt" : "35"},
{"mod" : "Lexus ES 330", "cnt" : "61"},
{"mod" : "Jeep Patriot", "cnt" : "82"},
{"mod" : "Volkswagen Tiguan", "cnt" : "18"},
{"mod" : "Ford Taurus", "cnt" : "36"},
{"mod" : "Kia Sorento", "cnt" : "65"},
{"mod" : "Chevrolet Trax", "cnt" : "18"},
{"mod" : "Chrysler Pacifica", "cnt" : "5"},
{"mod" : "Chevrolet Spark EV", "cnt" : "25"},
{"mod" : "Infiniti EX35", "cnt" : "13"},
{"mod" : "Honda Accord Hybrid", "cnt" : "14"},
{"mod" : "Chevrolet Express", "cnt" : "7"},
{"mod" : "Mitsubishi Mirage", "cnt" : "7"},
{"mod" : "Jaguar F-Type", "cnt" : "21"},
{"mod" : "Mazda 5", "cnt" : "47"},
{"mod" : "Lexus SC 430", "cnt" : "4"},
{"mod" : "Audi TT", "cnt" : "4"},
{"mod" : "Maserati Quattroporte", "cnt" : "21"},
{"mod" : "Mazda MAZDA2", "cnt" : "7"},
{"mod" : "Tesla Roadster", "cnt" : "40"},
{"mod" : "Jaguar F-TYPE", "cnt" : "30"},
{"mod" : "Jaguar XJ-Series", "cnt" : "2"},
{"mod" : "Chevrolet Traverse", "cnt" : "30"},
{"mod" : "Volkswagen Golf GTI", "cnt" : "16"},
{"mod" : "GMC Terrain", "cnt" : "22"},
{"mod" : "Acura RLX", "cnt" : "24"},
{"mod" : "Toyota FJ Cruiser", "cnt" : "27"},
{"mod" : "BMW 1 Series M", "cnt" : "7"},
{"mod" : "FIAT 500L", "cnt" : "24"},
{"mod" : "Lincoln Navigator", "cnt" : "22"},
{"mod" : "Lincoln MKC", "cnt" : "4"},
{"mod" : "Volkswagen e-Golf", "cnt" : "60"},
{"mod" : "Subaru BRZ", "cnt" : "8"},
{"mod" : "BMW 3 Series Gran Turismo", "cnt" : "38"},
{"mod" : "Cadillac Fleetwood", "cnt" : "16"},
{"mod" : "Subaru Legacy", "cnt" : "20"},
{"mod" : "GMC Sierra 1500HD", "cnt" : "2"},
{"mod" : "Cadillac SRX", "cnt" : "28"},
{"mod" : "BMW 5 Series Gran Turismo", "cnt" : "13"},
{"mod" : "Jeep Renegade", "cnt" : "10"},
{"mod" : "Porsche Macan", "cnt" : "7"},
{"mod" : "BMW X5 M", "cnt" : "22"},
{"mod" : "Chevrolet Colorado", "cnt" : "15"},
{"mod" : "Volvo XC60", "cnt" : "25"},
{"mod" : "Pontiac G6", "cnt" : "19"},
{"mod" : "Nissan Murano CrossCabriolet", "cnt" : "12"},
{"mod" : "Chevrolet Venture", "cnt" : "3"},
{"mod" : "Chevrolet Tahoe Hybrid", "cnt" : "10"},
{"mod" : "Volkswagen Beetle Convertible", "cnt" : "13"},
{"mod" : "Infiniti G37 Sedan", "cnt" : "32"},
{"mod" : "Infiniti M37", "cnt" : "12"},
{"mod" : "Buick Roadmaster", "cnt" : "14"},
{"mod" : "Mercedes-Benz GLE-Class Coupe", "cnt" : "29"},
{"mod" : "Scion xD", "cnt" : "30"},
{"mod" : "Chevrolet Avalanche", "cnt" : "17"},
{"mod" : "Porsche Cayman S", "cnt" : "5"},
{"mod" : "Honda Ridgeline", "cnt" : "12"},
{"mod" : "Honda Insight", "cnt" : "30"},
{"mod" : "Lexus RC F", "cnt" : "13"},
{"mod" : "Buick Lucerne", "cnt" : "19"},
{"mod" : "Fisker Karma", "cnt" : "9"},
{"mod" : "Subaru Impreza WRX", "cnt" : "10"},
{"mod" : "Infiniti Q60 Coupe", "cnt" : "17"},
{"mod" : "Honda S2000", "cnt" : "10"},
{"mod" : "Audi A3 Sportback e-tron", "cnt" : "5"},
{"mod" : "Mercedes-Benz 300 SEL", "cnt" : "7"},
{"mod" : "Aston Martin V8 Vantage", "cnt" : "11"},
{"mod" : "Mercury Milan", "cnt" : "8"},
{"mod" : "Chevrolet Uplander", "cnt" : "12"},
{"mod" : "Lexus RX 300", "cnt" : "6"},
{"mod" : "Jeep Liberty", "cnt" : "15"},
{"mod" : "Nissan Armada", "cnt" : "21"},
{"mod" : "Chevrolet Astro", "cnt" : "1"},
{"mod" : "FIAT 500X", "cnt" : "24"},
{"mod" : "Volvo V70", "cnt" : "17"},
{"mod" : "Volkswagen Vanagon", "cnt" : "5"},
{"mod" : "Mitsubishi Lancer", "cnt" : "16"},
{"mod" : "Hyundai Veracruz", "cnt" : "15"},
{"mod" : "Cadillac DTS", "cnt" : "12"},
{"mod" : "Pontiac G3", "cnt" : "12"},
{"mod" : "Infiniti Q40", "cnt" : "6"},
{"mod" : "Infiniti QX", "cnt" : "5"},
{"mod" : "BMW ALPINA B7", "cnt" : "11"},
{"mod" : "Ford Shelby GT500", "cnt" : "3"},
{"mod" : "Infiniti M", "cnt" : "21"},
{"mod" : "Lincoln MKS", "cnt" : "10"},
{"mod" : "Honda Crosstour", "cnt" : "15"},
{"mod" : "Toyota Avalon Hybrid", "cnt" : "6"},
{"mod" : "Isuzu Ascender", "cnt" : "1"},
{"mod" : "Dodge Ram Pickup 2500", "cnt" : "11"},
{"mod" : "Pontiac Vibe", "cnt" : "17"},
{"mod" : "Honda HR-V", "cnt" : "5"},
{"mod" : "HUMMER H1", "cnt" : "3"},
{"mod" : "Ford E-350", "cnt" : "6"},
{"mod" : "Acura RSX", "cnt" : "1"},
{"mod" : "BMW X6 M", "cnt" : "13"},
{"mod" : "BMW X5 eDrive", "cnt" : "26"},
{"mod" : "Ford Expedition EL", "cnt" : "3"},
{"mod" : "BMW 2002", "cnt" : "11"},
{"mod" : "Infiniti FX", "cnt" : "13"},
{"mod" : "Infiniti I35", "cnt" : "6"},
{"mod" : "MINI Cooper Paceman", "cnt" : "11"},
{"mod" : "Mercury Grand Marquis", "cnt" : "8"},
{"mod" : "Dodge Caliber", "cnt" : "3"},
{"mod" : "Chevrolet City Express", "cnt" : "7"},
{"mod" : "Mitsubishi Galant", "cnt" : "5"},
{"mod" : "Honda Accord Crosstour", "cnt" : "2"},
{"mod" : "Cadillac Escalade Hybrid", "cnt" : "10"},
{"mod" : "Mercedes-Benz R-Class", "cnt" : "3"},
{"mod" : "Toyota Highlander Hybrid", "cnt" : "7"},
{"mod" : "Dodge Neon", "cnt" : "4"},
{"mod" : "Lexus RX 450h", "cnt" : "3"},
{"mod" : "Infiniti QX56", "cnt" : "11"},
{"mod" : "Mercury Villager", "cnt" : "14"},
{"mod" : "Porsche 356 Speedster Replica", "cnt" : "10"},
{"mod" : "Acura ZDX", "cnt" : "7"},
{"mod" : "Mazda MPV", "cnt" : "6"},
{"mod" : "Toyota Land Cruiser", "cnt" : "8"},
{"mod" : "Hyundai Equus", "cnt" : "4"},
{"mod" : "Lincoln Mark LT", "cnt" : "3"},
{"mod" : "Lexus GS 300", "cnt" : "1"},
{"mod" : "Mercedes-Benz B-Class Electric Drive", "cnt" : "9"},
{"mod" : "Hyundai Tucson", "cnt" : "7"},
{"mod" : "Chevrolet TrailBlazer", "cnt" : "1"},
{"mod" : "Dodge Dakota", "cnt" : "2"},
{"mod" : "Lexus HS 250h", "cnt" : "5"},
{"mod" : "Saturn S-Series", "cnt" : "2"},
{"mod" : "Ford Transit Connect", "cnt" : "2"},
{"mod" : "HUMMER H1 Alpha", "cnt" : "3"},
{"mod" : "Suzuki XL7", "cnt" : "5"},
{"mod" : "Infiniti M45", "cnt" : "3"},
{"mod" : "Mazda Tribute", "cnt" : "1"},
{"mod" : "Audi S3", "cnt" : "1"},
{"mod" : "Chevrolet HHR", "cnt" : "1"},
{"mod" : "Pontiac Grand Am", "cnt" : "2"},
{"mod" : "Saturn VUE", "cnt" : "2"},
{"mod" : "Maserati GranTurismo", "cnt" : "6"},
{"mod" : "Chevrolet Cobalt", "cnt" : "2"},
{"mod" : "Audi RS 5", "cnt" : "2"},
{"mod" : "Lexus RC 200t", "cnt" : "1"},
{"mod" : "Audi SQ5", "cnt" : "1"},
{"mod" : "Volkswagen Rabbit", "cnt" : "1"},
{"mod" : "Mitsubishi Eclipse", "cnt" : "1"},
{"mod" : "Mitsubishi Lancer Sportback", "cnt" : "1"}
]
